postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: adminadmin
    POSTGRES_DB: office

office:
  image: imixs/office-workflow
  environment:
    WILDFLY_PASS: adminadmin
  ports:
    - "8080:8080"
    - "9990:9990"
  links: 
    - postgres:postgres
 

    
 